[package]
name = "vara"
version = "0.1.0"
edition = "2021"

[dependencies]
handlebars = "5.1.2"
ollama-rs = "0.1.9"
serde_json = "1.0.117"
structopt = "0.3.26"
tokio = { version = "1.37.0", features = ["full"] }
tokio-stream = "0.1.15"
